// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUVbwZhQFAGKFlLQQNeznR0XREoVzC_k',
    appId: '1:1071590133096:web:e8bd70440ac4b515bcdadd',
    messagingSenderId: '1071590133096',
    projectId: 'turikumwe-f0d31',
    authDomain: 'turikumwe-f0d31.firebaseapp.com',
    storageBucket: 'turikumwe-f0d31.firebasestorage.app',
    measurementId: 'G-SD6SB1TVPZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkDJXTPgrWgD-bse7__r-sgcnWXlowXTI',
    appId: '1:1071590133096:ios:04d96271d1ca4b81bcdadd',
    messagingSenderId: '1071590133096',
    projectId: 'turikumwe-f0d31',
    storageBucket: 'turikumwe-f0d31.firebasestorage.app',
    iosBundleId: 'com.example.turikumweApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkDJXTPgrWgD-bse7__r-sgcnWXlowXTI',
    appId: '1:1071590133096:ios:04d96271d1ca4b81bcdadd',
    messagingSenderId: '1071590133096',
    projectId: 'turikumwe-f0d31',
    storageBucket: 'turikumwe-f0d31.firebasestorage.app',
    iosBundleId: 'com.example.turikumweApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUVbwZhQFAGKFlLQQNeznR0XREoVzC_k',
    appId: '1:1071590133096:web:2dd150b4d4bbb81cbcdadd',
    messagingSenderId: '1071590133096',
    projectId: 'turikumwe-f0d31',
    authDomain: 'turikumwe-f0d31.firebaseapp.com',
    storageBucket: 'turikumwe-f0d31.firebasestorage.app',
    measurementId: 'G-BFLX414868',
  );
}
